//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTInstitucionFinanciera
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_form
    {
        public int Id { get; set; }
        public string type_credit_card { get; set; }
        public string credit_card_number { get; set; }
        public string name_holder { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public int customer_id { get; set; }
    }
}
