//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitucionFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoPago
    {
        public int Id { get; set; }
        public string tipoDocumento { get; set; }
        public string numDocumento { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> monto { get; set; }
    }
}
